name: iOS CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install xcbeautify

    - name: Setup Xcode 15
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

    - name: Test Pod build
      run: |
        pod install
        set -o pipefail && xcodebuild -workspace PodsTest.xcworkspace -scheme PodsTest -destination "platform=iOS Simulator,name=iPhone 15" test | xcbeautify
      working-directory: ios/PodsTest

    - name: Test SPM build
      run: |
        set -o pipefail && xcodebuild -project TrustWeb3Provider.xcodeproj -scheme TrustWeb3Provider-Example -destination "platform=iOS Simulator,name=iPhone 15" | xcbeautify
      working-directory: ios
