name: Web CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version:
        default: "1.0.0"
        description: New version number
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies and test
        run: |
          pnpm install
          pnpm run build
          NODE_ENV=test pnpm test
        working-directory: src
        env:
          NODE_ENV: test

  npm-release:
    name: NPM Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Install, build & publish
        run: |
          pnpm install
          pnpm run build
          npm version ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          npm run publish-npm-package
        working-directory: src
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@trustwallet"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build Project
        working-directory: src
        run: |
          pnpm install
          pnpm run build
          npm version ${{ github.event.inputs.version || steps.vars.outputs.tag  }}
          npm run prepare-publish

      - name: Publish
        working-directory: src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
